### PR TITLE
Stage two Volume settings

### PR DESCRIPTION
**Pull request by Robert-J-H**

### CODE REVIEW

**Comment by nvdaes** [comment]
Hi, the plugin is excellent for me, except that I will change "activation" name to a more descriptive name, reflecting that it's related to numLock.
The installTasks is using methods marked as private by underscore, and it may no be enough robust.
Furthermore, each time I start NVDA or the computer, the settings dialog is opened.
I wonder if we should create installTasks addressing all the changes introduced in configuration, as we have never posted a stable version on the website. Maybe...
Thanks for this geat work, @Robert-J-H

**Comment by Robert-J-H** [comment]
High Noelia

It's OK for me if you remove install tasks.
What do you mean by private functions, the __getitem__?
It's the only way to get a value without validation, apart from direct indexing.
You can also remove the three lines "First time install".
Curiously, I see the dialog really only if nothing is set.
We have to inform our quarter-dozen testers though about how to delete
the entry manually.

I wonder if the entry in the preference menu for the dialog shouldn't
just be called
"Shared Computer Settings"
The "Use" does in this context imply that settings of all users should
be used or something like this.
The name can be kept for the rest of the UI, although I would have chosen
"Use Shared Computer"
rather than the plural.

Have a nice start into the week

Robert

**Comment by nvdaes** [comment]
Hi, in fact I talk about __getItem__, and also _writeProfileToFile, not used though present preceded by #.
Perhaps we should name the add-on just shareComputer, without use, which maybe redundant.
I set configuration to defaults and install the add-on several times for testing. This can be done normally in NVDA. I think that, if we include installTasks, it should bring something different to the stardard settings dialog, some kind of extra explanation, and we could include a checkbox, like the Welcome dialog, asking if it should be shown at later installation, ince the user could choose to install the add-on several times expecting and wishing to see this dialog without using the Preferences dialog. if we use installTasks.
We can explain how to delete the extra keys inini files, but imo we shouldn't use protected names if possible, since they aren't intended for this and maybe removed from NVDA without noticing.
Have a good day, I will wait for your answer and can contribute to the installTasks if needed.

**Comment by Robert-J-H** [comment]
Hi

I think "sharedComputer" since "shareComputer" would again imply a
command or request, especially if you have
"Share Computer Settings".
There are other possibilities of course such as
"ComputerSharingAssistant", "NumlockAndVolumeManager" and what not
(how Joseph likes to say).
It's your Baby, so it is up to you.
I only know that the title will be hard to translate into German,
currently, the menu item would be
"instelungen für gemeinsame Computernutzung" but if you can find a
title that works with Spanish, that would be fine.

I have no qualms about using private functions. The underlying library
hasn't changed since 2011 and the public functions work only with
aggregated profiles which isn't of much use since you wanted to
exclude volume correction from all other profiles.

I agree that a different text would be indicated for a first
appearance of the dialog.
However, a checkbox might be overkill. It's one of those settings that
you'll get right once and then pretty much forget about it, which
would be a good sign of course.

Cheers
Robert

**Comment by nvdaes** [comment]
Hi, usually, the add-ons settings option in the Preferences menu ramains without being translated, like the add-on summary, at least in Spanish.
The translation in Spanish would be pretty uggly, imo.
About installTasks, I will think about this while I develop it, and then you can review it.
I think sharedComputer would be a valid name.

Cheers

**Comment by Robert-J-H** [comment]
Hi
That's another reason why I wanted a Swiss German variant of German.
We often use English or other proper names where the German
translation sounds too clumsy, e.g.Café for Kaffeehaus.
I look forward to your revision
Robert

**Comment by Robert-J-H** [comment]
Can you send me the log for your problem with writing to the normal
configuration, can it be caused by your introduction of the add-on
name constant?
I have no problems whatsoever.
Best
Robert

**Pull request merged**
